spring:
  application:
    name: "library-events-consumer"
  kafka:
    topics:
      library-events: "library-events-topic"
      library-events-group-id: "library-events-listener-group"
      library-events-retry: "library-events.RETRY"
      library-events-dql: "library-events.DLQ"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: postgres
    password: password
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

server:
  port: 8081