spring:
  application:
    name: "library-events-producer"
  kafka:
    topics:
      library-events: "library-events-topic"
    template:
      default-topic: "${spring.kafka.topics.library-events}"
    producer:
      bootstrap-server: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
